# Generated by Django 4.1.2 on 2022-11-01 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discu', '0003_discussion_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-update', '-created']},
        ),
    ]
